version: '3.4'

x-common-variables: &common-variables
  SERVICE_DISCOVERY_SERVER_ADDRESS: 192.168.0.12
  SERVICE_DISCOVERY_SERVER_PORT: 8500
  LOCAL_ADDRESS: 192.168.0.12
  PROFILES_ACTIVE: stage

services:
  consul:
    image: consul:latest
    command: "agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul-net
  gateway-service:
    image: tonsaito/gateway-service:latest
    ports:
      - "9080:9080"
    environment:
      <<: *common-variables
      REF_PORT: 9080
    networks:
      - gateway-net
  #client-api  ###########################################################################
  client-api-1:
    image: tonsaito/client-api
    environment:
      <<: *common-variables
      REF_PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - gateway-service
  #card-api ###########################################################################
#  card-api-1:
#    image: tonsaito/mtc-card-api:latest
#    environment:
#      <<: *common-variables
#      REF_PORT: 5100
#    ports:
#      - "5100:5100"
  #payment-api ###########################################################################
#  payment-api-1:
#    image: tonsaito/mtc-payment-api
#    environment:
#      <<: *common-variables
#      REF_PORT: 5200
#    ports:
#      - "5200:5200"
#  payment-api-2:
#    image: tonsaito/mtc-payment-api
#    environment:
#      <<: *common-variables
#      REF_PORT: 5201
#    ports:
#      - "5201:5201"
##invoice-api ###########################################################################
#  invoice-api-1:
#    image: tonsaito/mtc-invoice-api
#    environment:
#      <<: *common-variables
#      REF_PORT: 5300
#    ports:
#      - "5300:5300"

networks:
  consul-net:
    driver: bridge
  gateway-net:
    driver: bridge