version: '3.4'

services:
  consul:
    image: consul:latest
    command: "agent -server -ui -node=serverLocal -bootstrap-expect=1 -dev -client=0.0.0.0"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul-net-local

networks:
  consul-net-local:
    driver: bridge