server:
  port: 8888
spring:
  application:
    name: configuration-service
  cloud:
    consul:
      host: 192.168.0.12
      port: ${SERVICE_DISCOVERY_SERVER_PORT:8500}
      discovery:
        healthCheckUrl: http://192.168.0.12:${PORT:8888}/actuator/health
        healthCheckInterval: 15s
    config:
      server:
        git:
          uri: https://github.com/tonsaito/configuration-repo.git