server:
  port: 5200
  error:
    include-stacktrace: never

spring:
  application:
    name: payment-api
  cloud:
    consul:
      host: 192.168.0.12
      port: 8500
      discovery:
        healthCheckUrl: http://192.168.0.12:5200/actuator/health
        healthCheckInterval: 15s