server:
  port: ${PORT:9080}

spring:
  application:
    name: gateway-service
  profiles:
    active: stage
  cloud:
    consul:
      host: ${SERVICE_DISCOVERY_SERVER_ADDRESS}
      port: ${SERVICE_DISCOVERY_SERVER_PORT}
      discovery:
        prefer-ip-address: true
        healthCheckUrl: http://${LOCAL_ADDRESS}:${REF_PORT}/actuator/health
        healthCheckInterval: 15s
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: localhost-docker
            uri: ${LOCAL_ADDRESS}:${PORT:9080}

logging.level.com.netflix: DEBUG

management:
  security:
    enabled: false